window.alert("Olá Devs Senac")
window.alert("Esta é a minha primeira mensagem")
window.confirm("Está Gostando de Javascript")
window.prompt("Qual o seu nome?")
document.write("Estou escrevendo no corpo")